### ISSUE TITLE
Kein Problem, aber eine Anregung

### ISSUE THREAD

**Issue by Frogster78** [brdgm/ark-nova-solo-helper#18]
Hallo Stefan,

ich danke dir schon einmal für dein großartiges Projekt. Eine Spende wird definitiv kommen und dies habe ich noch nie gemacht!!

Ich habe eine kleine Anregung bzgl. der Arche Nova Solo App. Wenn es sich implementieren lässt, fände ich es sehr interessant, wenn ich bei 2 oder mehr ARNOs diesen unterschiedliche Level zuweisen könnte. So lässt sich der Unterschied in den Schwierigkeitsgraden vielleicht auch mal ein wenig vergleichen. 

Gestern habe ich zum ersten mal die 20/20/30/30 Verteilung probiert, dies fühlte sich auf jeden Fall etwas realistischer an. Ähnliches habe ich schon vorher getan, indem ich beim Würfeln die 6 ebenfalls für Aktion 5 genutzt habe. 
Ich werde mir bei meinen nächsten Partien mal eine Strichliste machen, wie häufig ich welche Position tatsächlich genutzt habe. Daraus ergibt sich dann ggf. eine andere prozentuale Verteilung. Gerne teile ich diese dir dann mit, wenn du interessiert bist.

Nochmal vielen Dank für deine Arbeit und liebe Grüße

Christian Seidel (christian.seidel@mail.de)

**Comment by stefanseifert** [comment]
danke! :)

ich habe in #19 die möglichkeit ergänzt den difficulty level per bot einzustellen, werde ich gleich als version 2.2.0 releasen.

(hinweis: github issues sind öffentlich für alle einsehbar, bitte ggf. die e-mail adresse aus deinem post entfernen, die ist für alle sichtbar inkl. spam bots & co)

**Comment by Frogster78** [comment]
Hallo Stefan, sau cool. Werde es gleich ausprobieren, wenn ich wieder aus
Schweden daheim bin.
Weather Machine habe ich auch schon 2x gespielt, aber die Saboteure sind
schon sau schwer zu besiegen oder ich habe den Dreh noch nicht raus.

Viele Grüße aus dem Westerwald

Christian

Stefan Seifert ***@***.***> schrieb am Di., 27. Juni 2023,
18:22:
