### ISSUE TITLE
Misleading picture for ARNO setup

### ISSUE THREAD

**Issue by K-oroviev** [brdgm/ark-nova-solo-helper#6]
Step 8 for ARNO setup indicates that you don't need dice while using the App, but the picture of the ARNO setup shows 6 dice, which can be a bit confusing. Is it posible to change the picture to one that shows no dice?

**Comment by stefanseifert** [comment]
yes, you're right - i took that photo from the original ARNO rules. i'll see to make an new one without that parts.

**Comment by stefanseifert** [comment]
fixed in v2.1.6 https://github.com/brdgm/ark-nova-solo-helper/commit/df65103f757eb6a6ad3162cd44827e2506a24697
